implement `-nnn` style flags in `argparse`
This implements support for numeric flags without an associated short or
long flag name. This pattern is used by many commands. For example `head
-3 /a/file` to emit the first three lines of the file.

Fixes #4214

diff --git a/tests/argparse.in b/tests/argparse.in
--- a/tests/argparse.in
+++ b/tests/argparse.in
@@ -31,6 +31,12 @@ begin
     argparse --name min-max --max-args 1 h/help -- arg1 arg2
 end
 
+echo '# Invalid "#-val" spec' >&2
+argparse '#-val=' -- abc -x def
+
+echo '# Invalid arg in the face of a "#-val" spec' >&2
+argparse '#-val' -- abc -x def
+
 ##########
 # Now verify that validly formed invocations work as expected.
 
@@ -64,3 +70,9 @@ begin
     set -l
     show $argv
 end
+
+echo '# A "#-val" spec works'
+argparse '#-val' -- abc -123 def
+set -l
+argparse 'v/verbose' '#-val' 't/token=' -- -123 a1 --token woohoo --234 -v a2 --verbose
+set -l
