modify `read` to require at least one var
Fixes #4220

diff --git a/tests/read.in b/tests/read.in
--- a/tests/read.in
+++ b/tests/read.in
@@ -2,6 +2,18 @@
 #
 # Test read builtin and IFS.
 #
+
+###########
+# Start by testing that invocation errors are handled correctly.
+echo '# Read with no vars is an error' >&2
+read
+echo '# Read with -a and anything other than exactly on var name is an error' >&2
+read -a
+read -a v1 v2
+read -a v1
+
+###########
+# Verify correct behavior of subcommands and splitting of input.
 count (echo one\ntwo)
 set -l IFS \t
 count (echo one\ntwo)
@@ -25,6 +37,7 @@ function print_vars --no-scope-shadowing
 end
 
 echo
+echo '# Test splitting input'
 echo 'hello there' | read -l one two
 print_vars one two
 echo 'hello there' | read -l one
@@ -41,6 +54,7 @@ echo -n 'a' | read -l one
 echo "$status $one"
 
 echo
+echo '# Test splitting input with IFS empty'
 set -l IFS
 echo 'hello' | read -l one
 print_vars one
