Add CI check for outdated translations

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,18 @@ jobs:
     - name: make fish_run_tests
       run: |
         make -C build VERBOSE=1 fish_run_tests
+    - uses: dtolnay/rust-toolchain@stable
+    - name: translation updates
+      run: |
+        # Ensure that fish is available as an executable.
+        sudo ln -s "$(pwd)/build/fish" /usr/bin/fish
+        # Required for our custom xgettext implementation.
+        cargo install --locked --version 1.0.106 cargo-expand
+        # Generate PO files. This should not result it a change in the repo if all translations are
+        # up to date.
+        build_tools/update_translations.fish --no-mo
+        # Show diff output. Fail if there is any.
+        git --no-pager diff --exit-code || { echo 'There are uncommited changes in the repo after regenerating the gettext PO files. Make sure to update them via `build_tools/update_translations.fish --no-mo` after changing source files.'; exit 1; }
 
   ubuntu-32bit-static-pcre2:
 
